primera_sec_hilos: primera_sec_hilos.c
	gcc primera_sec_hilos.c -o primera_sec_hilos -pthread
	./primera_sec_hilos
	rm primera_sec_hilos
	
primera_sec_proc: primera_sec_proc.c
	gcc primera_sec_proc.c -o primera_sec_proc -pthread
	./primera_sec_proc
	rm primera_sec_proc

segunda_sec_hilos: segunda_sec_hilos.c
	gcc segunda_sec_hilos.c -o segunda_sec_hilos -pthread
	./segunda_sec_hilos
	rm segunda_sec_hilos
	
segunda_sec_proc: segunda_sec_proc.c
	gcc segunda_sec_proc.c -o segunda_sec_proc -pthread
	./segunda_sec_proc
	rm segunda_sec_proc
	
	

	
