reserva_aulas_hilos: reserva_aulas_hilos.c
	gcc reserva_aulas_hilos.c -o reserva_aulas_hilos -pthread
	./reserva_aulas_hilos
	rm reserva_aulas_hilos
	
reserva_aulas_proc: reserva_aulas_proc.c
	gcc reserva_aulas_proc.c -o reservas_aulas_proc -pthread
	./reservas_aulas_proc
	rm reservas_aulas_proc
	
	

	
