banco_proc: banco_proc.c
	gcc banco_proc.c -o banco_proc -pthread
	./banco_proc
	rm banco_proc
	
banco_sem_hilos: banco_sem_hilos.c
	gcc banco_sem_hilos.c -o banco_sem_hilos -pthread
	./banco_sem_hilos
	rm banco_sem_hilos
	
	

	
